add jest
cherryontech/burnout-buster pull request #21
Opened 2023-02-22 23:58 UTC by vasconsaurus

### What github issue is this PR for, if any?
Resolves #4 

### What changed, and why?
Added jest to our project. Followed this doc:
https://nextjs.org/docs/testing#setting-up-jest-with-the-rust-compiler

Tested it with a failing and a passing test.
It seems to be working. 🙂 

To run tests: `npm run test`

2023-02-23 09:31 UTC, iilashi requested changes
Conflicting files: 
package-lock.json _(lines 19-26 & 1062-1092)_
package.json _(lines 21-28)_

Is it okay to merge and fix later?

2023-02-23 19:22 UTC, vasconsaurus commented
> Conflicting files: 
> package-lock.json _(lines 19-26 & 1062-1092)_
> package.json _(lines 21-28)_
> 
> Is it okay to merge and fix later? 

I'll update it, fix the conflicts, and update the pr 🙂

2023-02-26 17:50 UTC, vasconsaurus commented
I used this [post](https://blog.dennisokeeffe.com/blog/2021-10-27-jest-with-github-actions) for the action. It's pretty straightforward, only the cache part went over my head, I need to take a better look at that.

2023-03-02 21:26 UTC, iilashi approved these changes

2023-03-02 21:26 UTC, merged